### ISSUE TITLE
Where are pins B4 and B5 on the RP2040? For the PS/2 clock and data lines.

### ISSUE THREAD

**Issue by bluepylons** [joh/crkbd-trackpoint#2]
The README states the following for the Trackpoint connections:

> Make the following connections from the SK8707:
> 
>     PS/2 data line: connect to B4 on the RP2040
>     PS/2 clock line: connect to B5 on the RP2040

What pins are these referring to? I can't find any RP2040 boards with that pin naming scheme. Is B4 GPIO 9 (which is PWM4B), and is B5 GPIO 11 (which is PWM5B)?

**Comment by joh** [comment]
Hi, sorry that's confusing. Those refer to the corresponding pins on a regular pro micro. There is a [_pin_defs.h](https://github.com/joh/qmk_firmware/blob/joh-rp2040-trackpoint-pio-v4/keyboards/crkbd/keymaps/joh/_pin_defs.h) which maps them to the RP2040. In any case, B4 and B5 correspond to pins 8 and 9. I'll update the README :)
