### ISSUE TITLE
[QUESTION] pullups on the RP2040

### ISSUE THREAD

**Issue by tcastelly** [joh/crkbd-trackpoint#3]
Hi, 

Thank you very much for this documentation!

I'm confuse with one thing:
```txt
SK8707 does not require a reset circuit, but it does need pullups on the PS/2 data and clock lines. We can enable pullups on the RP2040 controller, so no extra resistors are needed.
```

What have I to do exactly?

Thank you again.

**Comment by joh** [comment]
Hi, I added a link to the commit which enables the pullups to the README :)

**Comment by tcastelly** [comment]
Thank you very much for your answer :)

Do we have to apply this change for all SK8707 models, or is it because you have a 5V one?

Thx again.

**Comment by joh** [comment]
Yes, pullups are needed regardless of the voltage level (5V/3.3V).
